ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views #basic_app i import ettim

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app')),
]

ProTwo/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.VisitorListView,name='visitor_list'),
    #path('<int:pk>/',views.VisitorDetailView.as_view(),name='visitor_detail'),
    path('visitor_create/',views.VisitorCreateView.as_view(),name='visitor_create'),
    path('visitor_update/<int:pk>/',views.VisitorUpdateView.as_view(),name='visitor_update'),
    path('<int:pk>/',views.VisitorDeleteView,name='visitor_delete'),

    path('appo_list/',views.AppointmentListView,name='appo_list'),
    path('appo_list/<int:pk>/',views.AppointmentDetailView.as_view(),name='appo_detail'),
    path('appo_create/',views.AppointmentCreateView.as_view(),name='appo_create'),
    path('appo_update/<int:pk>/',views.AppointmentUpdateView.as_view(),name='appo_update'),
    path('appo_delete/<int:pk>/',views.AppointmentDeleteView,name='appo_delete'),



]

ProTwo/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class  Visitor(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField(max_length=254,unique=True)
    company = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self): # Güncelleme formunu gönderdikten sonra sayfa tekrar list sayfasına yönlendirilecek
        return reverse('basic_app:visitor_update',kwargs={'pk':self.pk}) #----basic_app:visitor_list yazınca hata alıyorum


class Appointment(models.Model): #randevu modeli
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()     #örnek 2006-10-25 14:30 şeklinnde olucak
    subject = models.TextField()
    name = models.ForeignKey('basic_app.Visitor',on_delete= models.CASCADE) #Visitor modeline bağladım.

    def __str__(self):
        return self.name

    def get_absolute_url(self): # Güncelleme formunu gönderdikten sonra sayfa tekrar detail sayfasına yönlendirilecek
        return reverse("basic_app:appo_detail",kwargs={'pk':self.pk})

ProTwo/basic_app/forms.py
from django import forms
from .models import Visitor, Appointment


class VisitorForm(forms.ModelForm):

    class Meta:
        model = Visitor
        fields = ('name','email', 'company')

class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ('start_date','end_date', 'subject','name')

ProTwo/basic_app/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.urls import reverse_lazy,reverse
from django.http import HttpResponse
from . import models #aynı klasörün altında olduğu için . import models dedik.
from basic_app.forms import AppointmentForm,VisitorForm
from django.views.generic import (View,TemplateView,
                                 CreateView,UpdateView,
                                 ListView,DeleteView,
                                 DetailView )
# Create your views here.
class IndexView(TemplateView):#IndexView classını TemplateView classı ile genişlettik
    template_name = 'index.html'

def VisitorListView(request): #okul modelinde yer alan tüm okulları listeler
    context_object_name = 'visitor_details' # orijinal parametre adını (object_list) "context_object_name" ile başka bir şekilde adlandırabiliriz.
    model = models.Visitor
    visit_list = model.objects.all()
    paginator = Paginator(visit_list, 4) # Show 5 contacts per page
    page = request.GET.get('page')
    visitor_details = paginator.get_page(page)
    return render(request, 'basic_app/visitor_list.html', {'visitor_details': visitor_details})


class VisitorDetailView(DetailView): #okul veritabanında bulunan bir girdinin tüm detaylarını listelemesi için
    context_object_name = 'visitor_details'   #html sayfasında bu isimle çağıracağız.
    model = models.Visitor
    template_name = 'basic_app/visitor_detail.html'

class VisitorCreateView(CreateView):
    form_class = VisitorForm
    model = models.Visitor

class VisitorUpdateView(UpdateView):
    form_class = VisitorForm
    model = models.Visitor

def  VisitorDeleteView(request, pk):
    model = models.Visitor
    visitor_details = model.objects.get(pk=pk)
    visitor_details.delete()
    return redirect('/basic_app/')



def  AppointmentListView(request):
    context_object_name = 'appointments'
    model = models.Appointment
    app_list = model.objects.all()
    paginator = Paginator(app_list, 4) # Show 5 contacts per page
    page = request.GET.get('page')
    appointments = paginator.get_page(page)
    return render(request, 'basic_app/appo_list.html', {'appointments': appointments})


class AppointmentDetailView(DetailView):
    context_object_name = 'appo_details'
    model = models.Appointment
    template_name = 'basic_app/appo_detail.html'

class AppointmentCreateView(CreateView):

    form_class = AppointmentForm
    model = models.Appointment

class AppointmentUpdateView(UpdateView):

    form_class = AppointmentForm
    model = models.Appointment

def AppointmentDeleteView(request, pk):
   model = models.Appointment
   appo_details = model.objects.get(pk=pk)
   appo_details.delete()
   return redirect('/basic_app/appo_list')

ProTwo/basic_app/templates/basic_app/appo_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% load static %}
<div class="jumbotron">
{% block body_block %}

    <h1>Appointment Details:</h1>
    <table class="table">
      <thead class="alert-success">
        <tr>
          <th scope="col">Id_num</th>
          <th scope="col">Name</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Subject</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{appo_details.id}}</td>
          <td>{{appo_details.name}}</td>
          <td>{{appo_details.start_date}}</td>
          <td> {{appo_details.end_date}}</td>
          <td> {{appo_details.subject}}</td>
          <td><a class='btn btn-warning' href="{% url 'basic_app:appo_update' pk=appo_details.pk %}">Update</a>
              <a class='btn btn-danger' href="{% url 'basic_app:appo_delete' appo_details.id %}">Delete</a></td>
        </tr>
      </tbody>
    </table>
  </div>

   <script src="{% static 'crud/js/jquery-3.2.1.js'%}"></script>
   <script src="{% static 'crud/js/appo.js' %}"></script>

{% endblock %}

ProTwo/basic_app/templates/basic_app/appo_list.html
{% extends "basic_app/basic_app_base.html"  %}

{% block body_block %}
<h1>Welcome to list of all the Appointment!</h1>
<ol>
  {% for app in appointments %} <!--context_object_name-->

  <table class="table">
    <tbody>

      <tr>
        <td><h4><li><a href="{{app.id}}/"> {{ app.name }}</a></li></h4></td>
      </tr>

    </tbody>
  </table>
  {% endfor %}
</ol>



{% if appointments.has_other_pages %}
  <ul class="pagination">
    {% if appointments.has_previous %}
      <li><a href="?page={{ appointments.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in appointments.paginator.page_range %}
      {% if appointments.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if appointments.has_next %}
      <li><a href="?page={{ appointments.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

ProTwo/basic_app/templates/basic_app/appointment_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

ProTwo/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Calendar
      {% block title_block %}

      {% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



    <!--  Bootstrap 4 kodu  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:visitor_list' %}">Visitors</a>

        <a class="navbar-brand" href="{% url 'basic_app:appo_list' %}">Appointment</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:visitor_create' %}">Create Visitor</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:appo_create' %}">Create Appointment</a>

      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
  {# Plugins#}
  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script src="{% static 'crud/js/script.js' %}"></script>
  <script src="{% static 'crud/js/jquery-3.2.1.js'%}"></script>
 <script type="text/javascript" src="{% static 'js/master.js' %}"> </script> 

</html>

ProTwo/basic_app/templates/basic_app/visitor_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="">
  
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>

</div>
{% endblock %}

ProTwo/basic_app/templates/basic_app/visitor_list.html
{% extends "basic_app/basic_app_base.html"  %}
<div class="jumbotron">
{% load static %}
{% block body_block %}
<h1>Welcome to list of all the Visitors!</h1>

<ol>
  <table class="table">
    <thead class="alert-success">
      <tr>
        <th scope="col">Id_num</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Company</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
    {% for visitor in visitor_details %}
    <tr>
      <td>{{visitor.id}}</td>
      <td>{{visitor.name}}</td>
      <td>{{visitor.email}}</td>
      <td>{{visitor.company}}</td>
      <td><center><a class='btn btn-warning' href="{% url 'basic_app:visitor_update' visitor.id %}">Update</a>
             <a class="btn btn-sm btn-danger delete" href="{% url 'basic_app:visitor_delete' visitor.id %}">Delete</a></center></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

  </ol>

       <!--Paginator -->
  {% if visitor_details.has_other_pages %}
    <ul class="pagination">
      {% if visitor_details.has_previous %}
        <li><a href="?page={{ visitor_details.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in visitor_details.paginator.page_range %}
        {% if visitor_details.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if visitor_details.has_next %}
        <li><a href="?page={{ visitor_details.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
  <script src="{% static 'crud/js/jquery-3.2.1.js'%}"></script>
  <script src="{% static 'crud/js/script.js' %}"></script>

</div>

{% endblock %}

ProTwo/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Calendar

      {% block title_block %}

      {% endblock %}
    </title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



    <!--  Bootstrap 4 kodu  -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:visitor_list' %}">Visitors</a>
        <a class="navbar-brand" href="{% url 'basic_app:appo_list' %}">Appointment</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:visitor_create' %}">Create Visitor</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:appo_create' %}">Create Appointment</a>

      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
  {# Plugins#}

  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <script src="{% static 'crud/js/script.js' %}"></script>
  <script src="{% static 'crud/js/jquery-3.2.1.js'%}"></script>
  <script type="text/javascript" src="{% static 'js/master.js' %}"> </script>

</html>

ProTwo/templates/index.html
{% extends "base.html" %}
<div class="jumbotron">
{%  block body_block %}

  <h1> Home Page!</h1>

</div>
{% endblock %}